title: My Website
description: >
  Description for SEO
baseurl: ""

favicon-directory: /assets/favicon/
assets-directory: /assets/
image-directory: /assets/
empty-array: []

social:
  instagram: https://www.instagram.com/ACCOUNT
  facebook: https://www.facebook.com/ACCOUNT
  youtube: https://www.youtube.com/user/ACCOUNT
  linkedin: https://www.linkedin.com/in/ACCOUNT



plugins:
  - jekyll-feed

# permalink: pretty
# markdown: kramdown
# kramdown:
#     input: GFM
#
# paginate: 5
# paginate_path: "/some-path/page:num/"

defaults:
  - scope:
      path: ""
    values:
      layout: "page"
